#!/usr/bin/env bash
# GitLab-only: turn the discovered workspace entries into a dynamic child pipeline, one
# job-set (lint / build / test / coverage / link-drift) per entry. This is GitLab's
# equivalent of the GitHub `strategy.matrix` fan-out, and stays rename-proof because the
# entry list comes from discover-workspaces.sh at run time.
#
# Usage: gen-child-pipeline.sh [output.yml]      (default: child-pipeline.yml)

source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

out="${1:-child-pipeline.yml}"
here="$(dirname "${BASH_SOURCE[0]}")"

{
    cat <<'YAML'
# GENERATED by ci/scripts/gen-child-pipeline.sh — do not edit by hand.
default:
  image: "$CI_IMAGE"
  before_script:
    - export RUSTC_WRAPPER=sccache

stages: [check, report]

YAML

    while IFS= read -r entry; do
        slug="$(printf '%s' "$entry" | tr '/.' '--')"
        cat <<YAML
"lint:$entry":
  stage: check
  script:
    - cd "\$CI_PROJECT_DIR/$entry" && cargo clippy --all-targets || true

"build:$entry":
  stage: check
  script:
    - cd "$entry" && cargo build --locked || cargo build

"test:$entry":
  stage: check
  script:
    - cd "$entry" && cargo test

"coverage:$entry":
  stage: check
  script:
    - ci/scripts/coverage-full.sh "$entry"
  artifacts:
    paths: [".ci-coverage/"]
    expire_in: 1 week

YAML
    done < <("$here/discover-workspaces.sh" --lines)

    # Final job: merge every entry's lcov (collected as prior-stage artifacts) into one
    # report, expose the Cobertura report for MR line viz + the coverage % for the badge.
    cat <<'YAML'
"coverage:merge":
  stage: report
  script:
    - ci/scripts/merge-coverage.sh
  coverage: '/Coverage: \d+\.\d+%/'
  artifacts:
    paths: [".ci-coverage/html", ".ci-coverage/coverage.lcov"]
    reports:
      coverage_report:
        coverage_format: cobertura
        path: ".ci-coverage/cobertura.xml"
    expire_in: 1 week
YAML
} > "$out"

log "wrote child pipeline: $out"
