#!/usr/bin/env bash
# Compose the markdown "deployment notes" report used as the promotion PR/MR body and
# written to the job summary. Defensive: every section degrades to "n/a" if its source
# artifact is absent, so the report renders from whatever stages have run.
#
# Sources (all optional):
#   .ci-coverage/coverage.txt        total coverage line
#   .ci-report/tests.txt             per-entry test status (one "entry: PASS|FAIL" per line)
#   .ci-report/lint.txt              fmt/clippy summary
#   .ci-report/link-drift.txt        "OK" / failure detail
#   .ci-report/doc-suggestions.md    LLM doc suggestions
#
# Prints the report to stdout (redirect to a file for `gh pr --body-file`).

source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
cd "$REPO_ROOT"

read_or() { [ -f "$1" ] && cat "$1" || printf '%s' "$2"; }

sha="$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"
branch="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)"
coverage="$(read_or .ci-coverage/coverage.txt 'Coverage: n/a')"

cat <<EOF
## 🚀 Promotion report — \`$branch\` → \`master\`

**Commit:** \`$sha\`
**$coverage**

### ✅ Tests
$( if [ -f .ci-report/tests.txt ]; then
       sed 's/^/- /' .ci-report/tests.txt
   else echo "_no test summary captured_"; fi )

### 🎯 Lint
$(read_or .ci-report/lint.txt '_no lint summary captured_')

### 🔗 Workspace link drift
$(read_or .ci-report/link-drift.txt '_not run_')

### 📝 Documentation suggestions
$(read_or .ci-report/doc-suggestions.md '_no doc review run_')

---
_Generated by ci/scripts/gen-report.sh. Coverage counts dead code (LLVM region baseline)._
EOF
