// Developer logging: bring error!/warn!/info!/trace!/abort! into scope.
#[macro_use]
extern crate compositor_developer_debug_instance_record;

/// Raw libav (ffmpeg 8.x) bindings, generated by `build.rs` via bindgen.
#[allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    improper_ctypes
)]
pub mod ffi {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

mod common;
pub mod nvenc;
pub mod vaapi;

use std::path::PathBuf;

pub use nvenc::NvencEncoder;
pub use vaapi::VaapiEncoder;

/// Which hardware video backend to use. Selected by the `capture_encoder`
/// settings field (`mesa`/`vaapi` → VAAPI, anything else → NVENC). NVENC is the
/// path under test (NVIDIA has no VAAPI encode).
pub enum Backend {
    Nvenc,
    Vaapi,
}

pub fn backend_from_config() -> Backend {
    let encoder = &compositor_developer_environment_config_base::base::get().capture_encoder;
    match encoder.as_str() {
        "mesa" | "vaapi" => Backend::Vaapi,
        _ => Backend::Nvenc,
    }
}

/// A running video encode session — NVENC (readback-fed BGRA) or VAAPI
/// (zero-copy dmabuf).
pub enum CaptureEncoder {
    Nvenc(NvencEncoder),
    Vaapi(VaapiEncoder),
}

impl CaptureEncoder {
    /// NVENC consumes readback BGRA frames via `push`; VAAPI reads the dmabuf
    /// itself via `VaapiEncoder::encode`.
    pub fn needs_readback(&self) -> bool {
        matches!(self, Self::Nvenc(_))
    }

    pub fn finish(self) -> Option<PathBuf> {
        match self {
            Self::Nvenc(n) => n.finish(),
            Self::Vaapi(v) => v.finish(),
        }
    }

    pub fn discard(self) {
        match self {
            Self::Nvenc(n) => n.discard(),
            Self::Vaapi(v) => v.discard(),
        }
    }
}
