#!/usr/bin/env bash
# xwayland-satellite interactive launcher
# Walks through every HiDPI/scaling flag + optional xsettingsd setup.

set -euo pipefail

# ── ANSI helpers ──────────────────────────────────────────────────────────────
B=$'\e[1m' D=$'\e[2m' CY=$'\e[36m' GR=$'\e[32m' YL=$'\e[33m' RD=$'\e[31m' RS=$'\e[0m'
DIV="${D}────────────────────────────────────────────────────${RS}"
hr()  { printf '%s\n' "$DIV"; }
hdr() { printf '\n%s%s %s%s\n%s\n' "$B$CY" "──" "$*" "$RS" "$DIV"; }
dim() { printf '  %s%s%s\n' "$D" "$*" "$RS"; }
ok()  { printf '  %s✔%s %s\n' "$GR" "$RS" "$*"; }
warn(){ printf '  %s!%s %s\n' "$YL" "$RS" "$*"; }
err() { printf '  %s✖%s %s\n' "$RD" "$RS" "$*" >&2; }

# ── Auto-detect binary ────────────────────────────────────────────────────────
_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if   [[ -x "$_DIR/target/release/xwayland-satellite" ]]; then
  _DEFAULT_BIN="$_DIR/target/release/xwayland-satellite"
elif command -v xwayland-satellite &>/dev/null; then
  _DEFAULT_BIN="$(command -v xwayland-satellite)"
else
  _DEFAULT_BIN="xwayland-satellite"
fi

# ── Presets ───────────────────────────────────────────────────────────────────
# Fields: display | force_scale | ignore_frac | identity_vp | no_xsettings | x_res | log_scale | rust_log
PNAMES=(
  "empty"             "baseline"          "force-scale-1"
  "identity-viewport" "no-xsettings-dpi"  "ignore-fractional"
  "logical-resolution" "force+no-dpi"     "identity+no-dpi"
  "full-debug"
)
PDESCS=(
  "All fields unset — start from scratch"
  "All defaults — identical to current packaged behavior"
  "--force-scale 1.0 — freeze scale at 1× (neutralises Shape-A shrink)"
  "--identity-viewport — present buffer at native X pixel size"
  "--no-xsettings-dpi — cede DPI ownership to external xsettingsd"
  "--ignore-fractional-scale — integer wl_output scale only"
  "--x-resolution logical + --identity-viewport"
  "--force-scale 1.0 --no-xsettings-dpi — bypass both scaling stages"
  "--identity-viewport --no-xsettings-dpi"
  "baseline + --log-scale — instrumented run, nothing else changed"
)
PDATA=(
  "||false|false|false|physical|false|"       # empty
  "||false|false|false|physical|false|"       # baseline
  "|1.0|false|false|false|physical|true|"     # force-scale-1
  "||false|true|false|physical|true|"         # identity-viewport
  "||false|false|true|physical|true|"         # no-xsettings-dpi
  "||true|false|false|physical|true|"         # ignore-fractional
  "||false|true|false|logical|true|"          # logical-resolution
  "|1.0|false|false|true|physical|true|"      # force+no-dpi
  "||false|true|true|physical|true|"          # identity+no-dpi
  "||false|false|false|physical|true|debug"   # full-debug
)

# ── Prompt helpers ────────────────────────────────────────────────────────────
pfield() { local IFS='|'; read -ra _f <<< "$1"; printf '%s' "${_f[$2]:-}"; }

ask_yn() {          # ask_yn  "label"  default_bool → true|false
  local label=$1 def=$2 hint resp
  [[ "$def" == true ]] && hint="${GR}[Y/n]${RS}" || hint="${D}[y/N]${RS}"
  printf '  %s▶%s %s %b: ' "$YL" "$RS" "$label" "$hint" >&2
  read -r resp; [[ -z "$resp" ]] && resp="$def"
  case "${resp,,}" in y|yes|true|1) echo true ;; *) echo false ;; esac
}

ask_str() {         # ask_str  "label"  default → value
  local label=$1 def=$2 dfmt="" resp
  [[ -n "$def" ]] && dfmt=" ${D}(↵ = $def)${RS}"
  printf '  %s▶%s %s%b: ' "$YL" "$RS" "$label" "$dfmt" >&2
  read -r resp; echo "${resp:-$def}"
}

ask_choice() {      # ask_choice  "label"  default  opt...  → chosen
  local label=$1 def=$2; shift 2; local opts=("$@") resp opt
  local opts_str; opts_str="$(IFS='/'; echo "${opts[*]}")"
  printf '  %s▶%s %s [%s] %s(↵ = %s)%s: ' "$YL" "$RS" "$label" "$opts_str" "$D" "$def" "$RS" >&2
  read -r resp; [[ -z "$resp" ]] && resp="$def"
  for opt in "${opts[@]}"; do
    [[ "${resp,,}" == "${opt,,}" ]] && { echo "${opt,,}"; return; }
  done
  err "Unknown '${resp}', using '${def}'"; echo "$def"
}

# ── xsettingsd config writer ──────────────────────────────────────────────────
write_xsettingsd() {
  local file=$1 dpi=$2 gdk_scale=$3 gdk_undpi_raw=$4
  local xft_raw=$(( dpi * 1024 ))
  mkdir -p "$(dirname "$file")"
  cat > "$file" <<EOF
# Generated by xwayland-satellite launcher ($(date -Iseconds))
# Xft/DPI is stored as integer DPI × 1024 — $dpi DPI → $xft_raw
Xft/DPI $xft_raw
Gdk/WindowScalingFactor $gdk_scale
Gdk/UnscaledDPI $gdk_undpi_raw
EOF
  ok "Wrote ${file}"
}

# ─────────────────────────────────────────────────────────────────────────────
main() {

  # ── 1. Preset picker ─────────────────────────────────────────────────────
  printf '\n%s  xwayland-satellite — HiDPI/scaling launcher%s\n%s\n\n' \
    "$B$CY" "$RS" "$DIV"
  printf '  Pick a preset to prefill every field (you confirm each one):\n\n'
  local i
  for i in "${!PNAMES[@]}"; do
    printf '  %s%2d%s  %s%-22s%s  %s\n' \
      "$B" "$i" "$RS" "$GR" "${PNAMES[$i]}" "$RS" "${PDESCS[$i]}"
  done
  printf '\n'
  printf '  %s▶%s Preset [0–%d, ↵ = 0]: ' "$YL" "$RS" "$(( ${#PNAMES[@]} - 1 ))"
  read -r _pick; [[ -z "$_pick" ]] && _pick=0
  if ! [[ "$_pick" =~ ^[0-9]+$ ]] || (( _pick >= ${#PNAMES[@]} )); then
    err "Invalid choice — using 0 (empty)"; _pick=0
  fi
  local pdata="${PDATA[$_pick]}"
  printf '\n  Preset: %s%s%s  —  %s\n' \
    "$B$GR" "${PNAMES[$_pick]}" "$RS" "${PDESCS[$_pick]}"

  local p_display p_force p_ifrac p_ivp p_noxset p_xres p_log p_rustlog
  p_display=$(pfield "$pdata" 0); p_force=$(pfield "$pdata" 1)
  p_ifrac=$(pfield "$pdata" 2);   p_ivp=$(pfield "$pdata" 3)
  p_noxset=$(pfield "$pdata" 4);  p_xres=$(pfield "$pdata" 5)
  p_log=$(pfield "$pdata" 6);     p_rustlog=$(pfield "$pdata" 7)

  # ── 2. Binary ────────────────────────────────────────────────────────────
  hdr "Binary"
  local bin
  bin=$(ask_str "Path to xwayland-satellite" "$_DEFAULT_BIN")
  [[ ! -x "$bin" ]] && warn "'${bin}' not found / not executable — check path before running"

  # ── 3. Display ───────────────────────────────────────────────────────────
  hdr "Display"
  dim "X display to use (e.g. :1). Blank = Xwayland picks a free one."
  local display
  display=$(ask_str "Display (:N or blank)" "$p_display")

  # ── 4. --force-scale ─────────────────────────────────────────────────────
  hdr "--force-scale"
  dim "Override effective scale S with a constant.  1.0 = no scaling at viewport."
  dim "Blank = auto (current behaviour — derive from wl_output / wp_fractional_scale)."
  local force_scale
  force_scale=$(ask_str "Value (float, or blank to disable)" "$p_force")

  # ── 5. --ignore-fractional-scale ─────────────────────────────────────────
  hdr "--ignore-fractional-scale"
  dim "Skip binding wp_fractional_scale_manager; use only integer wl_output.scale."
  local ignore_frac
  ignore_frac=$(ask_yn "--ignore-fractional-scale?" "$p_ifrac")

  # ── 6. --identity-viewport ───────────────────────────────────────────────
  hdr "--identity-viewport"
  dim "wp_viewport destination = native X pixel size (no division by scale)."
  dim "Prevents logical shrink. 1:1 pixel mapping — may look blurry at HiDPI."
  local identity_vp
  identity_vp=$(ask_yn "--identity-viewport?" "$p_ivp")

  # ── 7. --no-xsettings-dpi ────────────────────────────────────────────────
  hdr "--no-xsettings-dpi"
  dim "Do not write Xft.dpi / Gdk DPI via XSETTINGS."
  dim "Satellite releases the _XSETTINGS_S0 selection so xsettingsd can own it."
  dim "Start xsettingsd AFTER satellite so it can grab the selection cleanly."
  local no_xsettings
  no_xsettings=$(ask_yn "--no-xsettings-dpi?" "$p_noxset")

  # ── 8. --x-resolution ────────────────────────────────────────────────────
  hdr "--x-resolution"
  dim "physical (default): xrandr always reports full physical resolution."
  dim "logical: Xwayland sees logical pixels — combine with --identity-viewport."
  local x_res
  x_res=$(ask_choice "--x-resolution" "$p_xres" physical logical)

  # ── 9. --log-scale ───────────────────────────────────────────────────────
  hdr "--log-scale"
  dim "Emit scale/viewport info at INFO level on every output change and configure."
  dim "Output: X geometry, effective_scale, viewport dst — use with dump_xsettings."
  local log_scale
  log_scale=$(ask_yn "--log-scale?" "$p_log")

  # ── 10. RUST_LOG ─────────────────────────────────────────────────────────
  hdr "RUST_LOG"
  dim "'debug' for full trace.  Blank = INFO only.  'debug' + --log-scale gives"
  dim "per-window viewport lines without the rest of the noise."
  local rust_log
  rust_log=$(ask_str "RUST_LOG (blank = info)" "$p_rustlog")

  # ── 11. xsettingsd ───────────────────────────────────────────────────────
  local use_xs=false xs_cfg="${HOME}/.xsettingsd"
  local xs_dpi=96 xs_gdk_scale=1 xs_gdk_undpi=98304

  if [[ "$no_xsettings" == true ]]; then
    hdr "xsettingsd"
    dim "With --no-xsettings-dpi, satellite won't write DPI settings."
    dim "xsettingsd can own _XSETTINGS_S0 and provide whatever DPI you want."
    printf '\n'
    use_xs=$(ask_yn "Configure and auto-launch xsettingsd?" "true")

    if [[ "$use_xs" == true ]]; then
      if ! command -v xsettingsd &>/dev/null; then
        err "xsettingsd not found — install it first (e.g.  sudo dnf install xsettingsd)"
        use_xs=false
      else
        printf '\n'
        dim "Xft/DPI in xsettingsd is stored as  DPI × 1024."
        dim "Common values:  96 (1×)   120 (1.25×)   144 (1.5×)   192 (2×)"
        xs_dpi=$(ask_str "Target DPI (integer)" "96")
        xs_dpi="${xs_dpi:-96}"

        printf '\n'
        dim "Gdk/WindowScalingFactor — GTK integer scale (usually 1 or 2)."
        local _auto_gdk=$(( xs_dpi / 96 ))
        [[ "$_auto_gdk" -lt 1 ]] && _auto_gdk=1
        xs_gdk_scale=$(ask_str "Gdk/WindowScalingFactor" "$_auto_gdk")
        xs_gdk_scale="${xs_gdk_scale:-$_auto_gdk}"

        printf '\n'
        local _auto_undpi=$(( (xs_dpi * 1024) / xs_gdk_scale ))
        dim "Gdk/UnscaledDPI — raw value = (DPI ÷ Gdk/WindowScalingFactor) × 1024."
        dim "Auto: ($xs_dpi ÷ $xs_gdk_scale) × 1024 = $_auto_undpi"
        xs_gdk_undpi=$(ask_str "Gdk/UnscaledDPI (raw integer)" "$_auto_undpi")
        xs_gdk_undpi="${xs_gdk_undpi:-$_auto_undpi}"

        printf '\n'
        xs_cfg=$(ask_str "xsettingsd config file" "${HOME}/.xsettingsd")

        # Preview the config
        printf '\n  %sConfig preview:%s\n' "$B" "$RS"
        printf '    %sXft/DPI %d\n' "$D" "$(( xs_dpi * 1024 ))"
        printf '    Gdk/WindowScalingFactor %d\n' "$xs_gdk_scale"
        printf '    Gdk/UnscaledDPI %d%s\n' "$xs_gdk_undpi" "$RS"

        printf '\n'
        local _write
        _write=$(ask_yn "Write config to ${xs_cfg} now?" "true")
        [[ "$_write" == true ]] && write_xsettingsd "$xs_cfg" "$xs_dpi" "$xs_gdk_scale" "$xs_gdk_undpi"

        if [[ -z "$display" ]]; then
          warn "No display specified — xsettingsd will need DISPLAY set."
          warn "Specify a display above, or set it manually after launch."
        fi
      fi
    fi
  fi

  # ── 12. Assemble command ──────────────────────────────────────────────────
  local -a args=()
  [[ -n "$display" ]]           && args+=("$display")
  [[ -n "$force_scale" ]]       && args+=(--force-scale "$force_scale")
  [[ "$ignore_frac" == true ]]  && args+=(--ignore-fractional-scale)
  [[ "$identity_vp" == true ]]  && args+=(--identity-viewport)
  [[ "$no_xsettings" == true ]] && args+=(--no-xsettings-dpi)
  [[ "$x_res" != "physical" ]]  && args+=(--x-resolution "$x_res")
  [[ "$log_scale" == true ]]    && args+=(--log-scale)

  local env_str=""; [[ -n "$rust_log" ]] && env_str="RUST_LOG=${rust_log} "
  local display_cmd="${env_str}${bin}"; local a
  for a in "${args[@]}"; do display_cmd+=" ${a}"; done

  hdr "Command"
  printf '\n  %s%s%s\n' "$B" "$display_cmd" "$RS"
  if [[ "$use_xs" == true ]]; then
    local _dnum="${display#:}"; [[ -z "$_dnum" ]] && _dnum="?"
    printf '  %s+ DISPLAY=:%s xsettingsd -c %s &%s\n' "$B$GR" "$_dnum" "$xs_cfg" "$RS"
  fi
  printf '\n'

  # ── 13. Dispatch ─────────────────────────────────────────────────────────
  hr
  printf '\n  %s[R]%s Run   ' "$B" "$RS"
  [[ "$use_xs" == true ]] && printf '%s[X]%s Run + xsettingsd   ' "$B" "$RS"
  printf '%s[C]%s Copy   %s[S]%s Summary   %s[Q]%s Quit\n\n' \
    "$B" "$RS" "$B" "$RS" "$B" "$RS"

  local _default="R"; [[ "$use_xs" == true ]] && _default="X"
  printf '  %s▶%s Action [↵ = %s]: ' "$YL" "$RS" "$_default"
  read -r _act; [[ -z "$_act" ]] && _act="$_default"

  case "${_act^^}" in

    R)  # ── run satellite only ───────────────────────────────────────────────
      printf '\n  %sLaunching...%s\n\n' "$GR" "$RS"
      printf " BIN = $bin"
      if [[ -n "$rust_log" ]]; then
        RUST_LOG="$rust_log" exec "$bin" "${args[@]}"
      else
        exec "$bin" "${args[@]}"
      fi
      ;;

    X)  # ── run satellite then xsettingsd ─────────────────────────────────────
      if [[ "$use_xs" != true ]]; then
        err "xsettingsd not configured — launching satellite only"
        exec "$bin" "${args[@]}"
      fi
      printf '\n  %sStarting satellite in background...%s\n' "$GR" "$RS"
      if [[ -n "$rust_log" ]]; then
        RUST_LOG="$rust_log" "$bin" "${args[@]}" &
      else
        "$bin" "${args[@]}" &
      fi
      local _sat_pid=$!
      local _dnum="${display#:}"; [[ -z "$_dnum" ]] && _dnum="0"

      printf '  Waiting for X socket /tmp/.X11-unix/X%s ...' "$_dnum"
      local _n=0
      while [[ ! -S "/tmp/.X11-unix/X${_dnum}" ]]; do
        sleep 0.5; (( _n++ ))
        if (( _n > 60 )); then
          printf '\n'; err "Timed out — start xsettingsd manually:"
          printf '    DISPLAY=:%s xsettingsd -c %s &\n' "$_dnum" "$xs_cfg"
          printf '  Satellite running as PID %s\n' "$_sat_pid"
          wait "$_sat_pid"; exit 0
        fi
        printf '.'
      done
      printf ' %s ready%s\n' "$GR" "$RS"

      printf '  %sStarting xsettingsd (DISPLAY=:%s)...%s\n' "$GR" "$_dnum" "$RS"
      DISPLAY=":${_dnum}" xsettingsd -c "$xs_cfg" &
      local _xs_pid=$!
      ok "xsettingsd PID ${_xs_pid}"
      ok "Verify: DISPLAY=:${_dnum} dump_xsettings"
      printf '\n  Satellite PID %s — Ctrl-C to stop both.\n' "$_sat_pid"

      # Forward SIGINT/SIGTERM to both
      trap "kill '$_sat_pid' '$_xs_pid' 2>/dev/null; exit" INT TERM

      wait "$_sat_pid"
      kill "$_xs_pid" 2>/dev/null || true
      ;;

    C)  # ── copy to clipboard ───────────────────────────────────────────────
      if   command -v wl-copy  &>/dev/null; then printf '%s' "$display_cmd" | wl-copy  && ok "Copied (wl-copy)"
      elif command -v xclip    &>/dev/null; then printf '%s' "$display_cmd" | xclip -sel clip && ok "Copied (xclip)"
      elif command -v xsel     &>/dev/null; then printf '%s' "$display_cmd" | xsel --clipboard --input && ok "Copied (xsel)"
      else err "No clipboard tool found (install wl-copy, xclip, or xsel)"; printf '  %s\n' "$display_cmd"
      fi
      ;;

    S)  # ── summary ──────────────────────────────────────────────────────────
      hdr "Summary"
      printf '  %-34s %s\n' "Binary:"                        "$bin"
      printf '  %-34s %s\n' "Display:"                       "${display:-(auto)}"
      printf '  %-34s %s\n' "--force-scale:"                 "${force_scale:-(disabled)}"
      printf '  %-34s %s\n' "--ignore-fractional-scale:"     "$ignore_frac"
      printf '  %-34s %s\n' "--identity-viewport:"           "$identity_vp"
      printf '  %-34s %s\n' "--no-xsettings-dpi:"            "$no_xsettings"
      printf '  %-34s %s\n' "--x-resolution:"                "$x_res"
      printf '  %-34s %s\n' "--log-scale:"                   "$log_scale"
      printf '  %-34s %s\n' "RUST_LOG:"                      "${rust_log:-(info)}"
      if [[ "$no_xsettings" == true ]]; then
        printf '  %-34s %s\n' "xsettingsd enabled:"          "$use_xs"
        if [[ "$use_xs" == true ]]; then
          printf '  %-34s %d DPI  →  Xft/DPI %d\n' \
            "xsettingsd DPI:" "$xs_dpi" "$(( xs_dpi * 1024 ))"
          printf '  %-34s %d\n' "  Gdk/WindowScalingFactor:" "$xs_gdk_scale"
          printf '  %-34s %d\n' "  Gdk/UnscaledDPI (raw):"   "$xs_gdk_undpi"
          printf '  %-34s %s\n' "  config file:"             "$xs_cfg"
        fi
      fi
      ;;

    Q)  printf '\n  Aborted.\n'; exit 0 ;;
    *)  err "Unknown action '${_act}'"; exit 1 ;;
  esac
}

main "$@"
