//! Per-preset session file text generators (wrapper script, systemd service,
//! shutdown target, wayland-session entry), modeled on the live reference captures
//! kept under .reference/references/ (live-installation-example-files/ and installer-artifact/).

use compositor_installer_process_config_parse_base::Preset;

/// The /usr/bin wrapper script: exports session identity + a few third-party
/// debug vars, then writes the compositor's settings.json (the only place the
/// compositor's config is supplied), then execs the compositor binary.
pub fn wrapper_desktop(p: &Preset) -> String {
    format!(
        "#!/bin/bash\n\
         # /usr/bin/{wrapper} — ExecStart of {service}\n\
         # Generated by the y5 installer. Re-run the installer to regenerate.\n\
         \n\
         export RUST_LOG=info,smithay=info\n\
         export MESA_DEBUG=1\n\
         \n\
         # Session identity — must match DesktopNames= in the wayland-session entry.\n\
         export XDG_CURRENT_DESKTOP={desktop}\n\
         export XDG_SESSION_TYPE=wayland\n\
         \n\
         # The compositor reads ALL of its configuration from this file (every field\n\
         # required; it panics if the file is missing or partial).\n\
         _y5_cfg=\"${{XDG_CONFIG_HOME:-$HOME/.config}}/y5.compositor\"\n\
         mkdir -p \"$_y5_cfg\"\n\
         cat > \"$_y5_cfg/settings.json\" <<'Y5_SETTINGS_EOF'\n\
         {json}\n\
         Y5_SETTINGS_EOF\n\
         \n\
         exec /usr/bin/{binary}\n",
        wrapper = p.wrapper,
        service = p.service,
        desktop = p.desktop_name,
        json = p.env.to_json(),
        binary = p.binary,
    )
}

/// systemd user service (modeled on the reference y5.*.service units).
pub fn systemd_service(p: &Preset) -> String {
    format!(
        "# ~/.config/systemd/user/{service}\n\
         [Unit]\n\
         Description=Y5 Wayland compositor ({label})\n\
         BindsTo=graphical-session.target\n\
         Before=graphical-session.target\n\
         Wants=graphical-session-pre.target\n\
         After=graphical-session-pre.target\n\
         Wants=xdg-desktop-autostart.target\n\
         Before=xdg-desktop-autostart.target\n\
         \n\
         [Service]\n\
         Slice=session.slice\n\
         Type=exec\n\
         ExecStart=/usr/bin/{wrapper}\n",
        service = p.service,
        label = p.label,
        wrapper = p.wrapper,
    )
}

/// The shutdown target paired with each session (from the reference).
pub fn shutdown_target() -> String {
    "[Unit]\n\
     Description=Shutdown running Y5 session\n\
     DefaultDependencies=no\n\
     StopWhenUnneeded=yes\n\
     Conflicts=graphical-session.target graphical-session-pre.target\n\
     After=graphical-session.target graphical-session-pre.target\n"
        .to_string()
}

/// /usr/share/wayland-sessions entry the display manager lists.
pub fn wayland_session(p: &Preset) -> String {
    format!(
        "[Desktop Entry]\n\
         Name={name}\n\
         Comment=Y5 Compositor — {label}\n\
         Exec=systemctl --user --wait start {service}\n\
         Type=Application\n\
         DesktopNames={desktop}\n",
        name = p.session_name,
        label = p.label,
        service = p.service,
        desktop = p.desktop_name,
    )
}
